// text for using
//구조 재구성 필요 -> q_a_2, q_a_2_2처럼? 혹은 다른 구조로
//
//현재는 테스트를 위해 임시로 작성한 내용, 피그마와 맞지 않는 부분 상당부분
//

import images from '../img';
const TxtCollection = {
  q_d_1: {
    level: 1,
    imgPath: images.null,
    quiestionType: 'Threeline_Picker',
    questionId: 'Q_Default_1',
    questionTitle_First: '나는',
    questionTitle_Second: '에',
    questionTitle_Third: '태어났어',
    pickerType_Frist: 'datePicker',
    pickerType_Second: 'None',
    nextpage: 'Q_Default_2',
  },
  q_d_2: {
    level: 2,
    imgPath: images.null,
    quiestionType: 'Button_Selector',
    questionId: 'Q_Default_2',
    questionTitle: '나는',
    // questionTitle_First:'나는',
    // questionTitle_Second: null,
    // questionTitle_Third: null,
    count: 5,
    contents: [
      '난소 건강을 유지하고 싶어',
      '난자 냉동 계획이 있어',
      '난임 시술 계획이 있어',
      '현재 시술을 하고 있어 (난자 냉동, 난임 시술)',
      '갱년기 준비와 관리를 하고 싶어',
    ],
    nextpage: 'Q_Default_3',
  },
  q_d_3: {
    level: 3,
    imgPath: images.null,
    quiestionType: 'Button_Selector',
    questionId: 'Q_Default_3',
    questionTitle: '나는',
    // questionTitle_First:'나는',
    // questionTitle_Second: null,
    // questionTitle_Third: null,
    count: 5,
    contents: [
      '결혼을 안 했어',
      '결혼을 했어',
      '임신 준비 중이야',
      '자녀가 있어',
      '임신 중이야',
    ],
    nextpage: ['Q_userA_1', 'Q_userB_1', 'Q_userC_1'],
  },

  //임시
  q_a_1: {
    level: 4,
    imgPath: images.userA,
    quiestionType: 'Button_Selector',
    questionId: 'Q_userA_1',
    questionTitle: '나는',
    // questionTitle_First:'나는',
    // questionTitle_Second: null,
    // questionTitle_Third: null,
    count: 3,
    contents: ['결혼하고 싶어', '결혼 생각이 없어', '아직 잘 모르겠어'],
  },
  q_a_1_1: {
    level: 4,
    imgPath: images.userA,
    quiestionType: 'Threeline_Picker',
    questionId: 'Q_userA_1_1',
    // questionTitle: '나는',
    questionTitle_First: '나는',
    questionTitle_Second: '살쯤에',
    questionTitle_Third: '결혼하면 좋겠어',
    pickerType_Frist: 'numberPicker',
    pickerType_Second: 'None',
  },
  q_a_2: {
    level: 5,
    imgPath: images.userA,
    quiestionType: 'Button_Selector',
    questionId: 'Q_userA_2',
    questionTitle: '나는 아이를',
    // questionTitle_First:'나는',
    // questionTitle_Second: null,
    // questionTitle_Third: null,
    count: 2,
    contents: ['갖고 싶어', '갖고 싶은 생각이 없어'],
  },
  q_a_2_1: {
    level: 5,
    imgPath: images.userA,
    quiestionType: 'Threeline_Picker',
    questionId: 'Q_userA_2_1',
    // questionTitle: '나는',
    questionTitle_First: '나는',
    questionTitle_Second: '살에',
    questionTitle_Third: '첫째 아이를 갖고 싶어',
    pickerType_Frist: 'numberPicker',
    pickerType_Second: 'None',
  },
  q_a_2_2: {
    level: 5,
    imgPath: images.userA,
    quiestionType: 'Button_Selector',
    questionId: 'Q_userA_2_2',
    questionTitle: '나는',
    // questionTitle_First:'나는',
    // questionTitle_Second: null,
    // questionTitle_Third: null,
    count: 2,
    contents: ['아이를 1명만 갖고 싶어', '둘째도 갖고 싶어'],
  },
  q_a_2_3: {
    level: 5,
    imgPath: images.userA,
    quiestionType: 'Threeline_Picker',
    questionId: 'Q_userA_2_3',
    // questionTitle: '나는',
    questionTitle_First: '나는',
    questionTitle_Second: '살에',
    questionTitle_Third: '둘째 아이를 갖고 싶어',
    pickerType_Frist: 'numberPicker',
    pickerType_Second: 'None',
  },
  q_a_3: {
    level: 6,
    imgPath: images.userA,
    quiestionType: 'Button_Selector',
    questionId: 'Q_userA_3',
    questionTitle: '나는 난자 냉동을',
    // questionTitle_First:'나는',
    // questionTitle_Second: null,
    // questionTitle_Third: null,
    count: 4,
    contents: [
      '이미 해서 보관 중이야',
      '하지 않았지만, 관심 있어',
      '하지 않았고, 별로 관심 없어',
      '잘 모르고 있어',
    ],
  },
  q_a_4_1: {
    contents: ['규칙적이야', '불규칙적이야'],
  },
  q_a_type: {
    questionId: 'Q_userA_Type',
    title: '여유로운 똑똑이 유형',
    description: [
      '하해호님에게 맞는 콘텐츠를 추천해드려요.',
      '다음 설문에 답변해보세요',
    ],
    imgPath: images.userA,
  },
  hq_1: {
    title: '나는 여성호르몬 검사를',
    contents: [
      '해봤고, 내 상태를 알아',
      '알고 있지만, 해 본 적 없어',
      '잘 모르고 있어',
    ],
  },
};

export default TxtCollection;
